### ISSUE TITLE
Add Season/Episode number & Episode title

### ISSUE THREAD

**Issue by tunip** [pipelka/roboTV#11]
Found some interesting options in the development guide.

Class TvContract.Programs

COLUMN_SEASON_NUMBER
-> VDR event season number

COLUMN_EPISODE_NUMBER
-> VDR event episode number

COLUMN_EPISODE_TITLE
-> VDR event „short description“

COLUMN_SHORT_DESCRIPTION
-> VDR event „description“ only.

If VDR „short description“ is moved to COLUMN_EPISODE_TITLE, then no longer merging of VDR „short description“ and „description“ is required.

Here is an example:
![live_channels-1](https://cloud.githubusercontent.com/assets/11404472/13379502/63ca2830-de27-11e5-92e9-f6b0d43e0186.jpg)

![live_channels-2](https://cloud.githubusercontent.com/assets/11404472/13379489/1bbb83fe-de27-11e5-9b00-aacac7f6e185.jpg)

Keep up the good work!

**Comment by pipelka** [comment]
I will try this (as soon as i find some time) and post screenshots. Looks promising.

**Comment by tunip** [comment]
I have installed Android Studio and tried to add COLUMN_EPISODE_TITLE.

![live channels_episode_title](https://cloud.githubusercontent.com/assets/11404472/13544123/dd9fed4e-e272-11e5-9a0f-ab8a29604b07.jpg)
![live channels_episode_title_2](https://cloud.githubusercontent.com/assets/11404472/13544124/e01626e2-e272-11e5-854d-e7a816b93c93.jpg)

**Comment by pipelka** [comment]
Oh. Great. Do you have a PR for me ?

**Comment by pipelka** [comment]
Really an improvement. Thanks a lot.
