### ISSUE TITLE
Logical Channel Numbers (LCN)

### ISSUE THREAD

**Issue by smoothquark** [pipelka/roboTV#12]
I don't think neither vdr-plugin-xvdr nor roboTV supports Logical Channel Numbers (LCN)? Eg.:

:@101
BBC One HD;BSkyB:10847:VC23M5O25P0S1:S28.2E:23000:5400=27:5402=NAR@3;5401=eng@106:5403;5404=eng:0:6941:2:2050:0
:@102
BBC Two HD;BSkyB:10847:VC23M5O25P0S1:S28.2E:23000:5500=27:5502=NAR@3;5501=eng@106:5503;5504=eng:0:6940:2:2050:0

Support for this would be most welcome.

**Comment by pipelka** [comment]
I'm quite sure you will have duplicated channel id's in your list but it's absolutely doable. I'll add support for this to the new robotv vdr plugin.

**Comment by pipelka** [comment]
Implemented in 0.4.0.
