### ISSUE TITLE
Installing 0.3 fails

### ISSUE THREAD

**Issue by swttt** [pipelka/roboTV#13]
Installing the 0.3 apk fails. (Crashes on start up.)
Need to install 0.2 first and then upgrade to make 0.3 work (Shield TV).

**Comment by pipelka** [comment]
I'm unabled to reproduce that. You you have any logs of the crash (adb logcat) to analyse ?
PS: Sorry for the late reply.

**Comment by swttt** [comment]
I'll try to reproduce and get a log.

To explain myself a bit more:
I tried to install 0.3 trough the ES, it installs fine but can't load the config to add channels (Crashed).
Deleted 0.3 and installed 0.2, which worked fine. Then "upgraded" the 0.2 to 0.3, and works fine as well.

I'll try to get some logs for you.

**Comment by pipelka** [comment]
As there is not enough information I'll close this issue.
If there are any logs available please open a new issue.
