### ISSUE TITLE
Channel icons not working/showing

### ISSUE THREAD

**Issue by swttt** [pipelka/roboTV#15]
Can't seem to get channel icons working.
Tried these xvdr.conf:
PiconsURL = file:///epgdata/picons2
PiconsURL = /epgdata/picons2

Something I'm missing here? Read something about running them on a web server, is this necessary?

**Comment by tunip** [comment]
Your Android TV device should start with something like /sdcard for your local storage.

On SATV (full path in your case for picons):
PiconsURL = /sdcard/epgdata/picons2

Running them on a webserver is not necessary.

**Comment by swttt** [comment]
Thank you Tunip, will try later today.

Just noticed my xmltv grabber has an icon entry with the channel logo. 
Any chance this could be added as a setting? Example:

 `<channel id="1-veronica">
    <display-name lang="nl">Veronica / Disney XD</display-name>
    <icon src="http://212.142.41.211/ChannelLogos/02/veronica_disney_xd2.png"/>
  </channel>`

**Comment by swttt** [comment]
Can't seem to get it work.
I am trying it with this script to generate the picons: https://github.com/picons/picons-source
Generated as SRP (example: 1_0_19_1B6F_C88_3_EB0000_0_0_0.png for this channel RTL5 HD;M7 Group:11856:vC23M5O25S1:S23.5E:27500:523=27:0;83:33:1817,100,500:7023:3:3208:0:RTL 5)

What am i doing wrong? Should i use channel names in stead? (Tried it, but maybe not enough.)

**Comment by tunip** [comment]
I will try this weekend your setup. I use a webserver for picons, because I have more then one device and don't want copy the picons (in case of channel updates) to all devices manually.

Please be reminded if you change your config (e.g. PiconsURL in conf-file) you have to reimport your channels in Live Channels app.

**Comment by swttt** [comment]
Well, tried numerous things. Then ended up doing the same thing as you, created a web server to feed the picons. 

Works as a charm.

Thanks for the help though!

**Comment by tunip** [comment]
I can confirm that channel icons are only working with a webserver. Tried also a lot things.

**Comment by mattgorski** [comment]
@swttt 
What was the channel naming convention you all used?  Channel Name Channel Number or Picons Channel Name ie 1_0_19_1B6F_C88_3_EB0000_0_0_0.png
