### ISSUE TITLE
Notification size

### ISSUE THREAD

**Issue by tunip** [pipelka/roboTV#18]
Since I use roboTV the notification size in the right bottom corner is very small. Font size would be OK, but the blue "toast" has always the same small size.

![live channels_notification](https://cloud.githubusercontent.com/assets/11404472/14720575/6623723a-0802-11e6-8354-ec2fa6e907a2.jpg)

**Comment by pipelka** [comment]
Very strange. But possibly a problem with the toast layout.
Please check if 0956116 makes any difference.

**Comment by tunip** [comment]
Thanks for your branch. I have tested it and roboTV crashes with a grey message in the center ("robotTV" wurde beendet.) if a toast would popup (ie, start a record on the server).
After restart i see a small blue emtpy toast.

**Comment by pipelka** [comment]
Ok. I forgot to mention that the git version always needs the "master" branch of the vdr plugin. This will change when the vdr plugin reaches version 1.0.

**Comment by tunip** [comment]
vdr plugin is git master branch.

**Comment by pipelka** [comment]
When using a different preview device (TV layout) in the layout editor of Android Studio i see the very small notification size. Unfortunately it looks ok on the Shield and Nexus devices for me.
I try to set the display density manually. Please check if 328a5eff1d78b7e7ef8d5606e878b536cd163ab1 looks better for you.

**Comment by tunip** [comment]
Would like to build, but my setup did not work anymore since upgrade of Android Studio and components.

Gradle build finished with 22 error(s) and 4 warning(s) in 3s 682ms

**Comment by pipelka** [comment]
Android Studio's NDK support is pretty dumb. Since 2.0 it uses NDK 12 Beta which seems to be broken for C++11.
I solved the problem by downloading NDK 10 (current NDK 11 also works) and setting the path in the "Project Structure".

See here:
![studio-ndk](https://cloud.githubusercontent.com/assets/584386/14861761/e56cbe24-0cae-11e6-9991-15bd8bd3696d.png)

**Comment by pipelka** [comment]
Please try this snapshot (we be the upcoming 0.5.0 release):
https://www.dropbox.com/s/ie1vtt8l6m6ijo6/robotv-master-d1af99f-release.apk?dl=0

**Comment by tunip** [comment]
Thanks for this snapshot. Tried it and Live Channels app crashed (unresponsive for a few seconds then the crash toast is shown) on channel change. Sometimes it runs, then I record a program to force a toast message, then robotTV app crashes (without a toast message). Cleared app cache for both apps, vdr-plugin is a git snapshot from yesterday. I also deleted the vdr-plugin database, both apps crashing again.

How can I send you a debug log? Maybe it would help.

**Comment by pipelka** [comment]
If you are using the latest version of the "Live Channels" app please try to revert to the version originally installed on your system. It seems the latest version is totally bogus.

A log of the crash can be captured with "adb logcat".

**Comment by tunip** [comment]
Size of the toast messages are still small. Can't see text inside the toats.

**Comment by pipelka** [comment]
I'm a bit confused, it works in the Emulator, it works on the Nexus Player, it works on my Shield TV.
The question is: What is different on your setup ?
Do you use some unusual HW, other Firmware versions, whatever ?

**Comment by tunip** [comment]
My setup:

Hardware:
2x NVIDIA Shield Android TV 16 GB
Living room: LG Beamer 
Bed room:   Samsung TV 

Software:
NVIDIA Shield Version 3.1 (latest official)
VDR 2.2 with latest git-revision of vdr-robotv-plugin

Starting VDR within a docker as user (not root):
vdr --chartab=ISO-8859-15 -P"satip -d 4 -s 10.10.11.1|DVBS2-4|OctopusNet -p 34001-34010" -Pdvbapi -Pstreamdev-server -Probotv -Pepg2vdr -P"remote -p tcp:3333"
1. Factory reset of the Shield TV
2. Language "Deutschland"
3. Login with my google account
4. Waiting for all app updates
5. Disable automatic updates in Play Store, then deinstalling Live Channels update
6. Installing ES File Explorer from Play Store and setup to use my NAS (SMB)
7. Installing roboTV snapshot from this thread with ES File Explorer from network drive (also tried from local drive)
8. Configure roboTV with IP-address to VDR server, Deutsch, 5.1 (Living room), stereo (Bed room ), passthrough: no, then get channels.

After a few minutes I have full EPG with channel icons for my 109 channles.
Watching tv works fine.
Change channels works stable after deinstalling Live Channels update.

If i then record or delete a show inside of roboTV app, toast message comes sometimes up in the bottom right corner with small size on both devices. Will do more testing with logging.

I try a temporary installation of VDR server with a simple setup (new setup.conf) on a separate hardware with only 2 plugins (satip, robotv). I need satip-plugin, because tuner is not in the same server.

**Comment by pipelka** [comment]
Thanks for the detailed description of your setup ;-)

One thing:

> If i then record or delete a show inside of roboTV app, toast message comes sometimes up in the bottom right corner with small size on both devices.

Means "sometimes" that the toast messages are usually ok but sometimes they are small ?

**Comment by pipelka** [comment]
Hold your horses !
I think i found it. I'm a complete jerk, ...
I didn't use resolution-agnostic units in the xml layout.
I will prepare a new snapshot.

**Comment by pipelka** [comment]
Here we go:
https://www.dropbox.com/s/fysa8jf58kocaq5/robotv-master-60dad94-release.apk?dl=0

Hopefully, this one will fix the problem.

**Comment by tunip** [comment]
First of all, you are the man :-)... Toast size is now good. Also the import channels (the progress bar if you press "Kanäle importieren") looks now correct. Before the progress bar was in middle of the screen inside of the text 👍.

![live channels_toast](https://cloud.githubusercontent.com/assets/11404472/15334147/3a49d06c-1c6d-11e6-9a4f-de3722de57c1.jpg)
Font size is nano to big.

Many thanks for you effort.

**Comment by pipelka** [comment]
Oh, great. I really thought this issue will drive me crazy.
I'll align the text a bit to fully fit into the notification.
This means it's time create a new release. Thanks for doing all the testing.

Closing, ..,
