### ISSUE TITLE
live TV is not responding

### ISSUE THREAD

**Issue by reinhard-brandstaedter** [pipelka/roboTV#19]
After I switched to 0.9.100 robotv vdr plugin and 0.5.0 robotv I keep getting errors on my NV Shield that live channels is not responding and roboTV hangs.
When I restart it it works for some minutes and then it hangs again.
There are no error messages on the VDR side, everything looks fine.
How can I get debug info on the client side for details?

**Comment by pipelka** [comment]
This happens with the latest version of the "Live Channel" app. Please try to revert the "Live Channels" app to the version originally installed on your system.

**Comment by reinhard-brandstaedter** [comment]
Yes, that worked, thanks!
