### ISSUE TITLE
Refreshrate switching

### ISSUE THREAD

**Issue by tunip** [pipelka/roboTV#20]
Set my SHIELD to 60 Hz for playing games over gamestream. With 50 Hz and ethernet connection you can't connect the SHIELD game controller. Thats the reason for setting the device to 60 Hz.

As I remember, a few roboTV versions ago, there was a refreshrate setting option in the app. I cant find it now (0.5.0). Can only set the language to "Deutsch". How can I enable refreshrate switching in roboTV?

Thx

**Comment by pipelka** [comment]
Unfortunately this workaround doesn't work for the Shield TV and it only worked for apps using API Level 22 (Android L). That's the reason for removing it.

**Comment by pipelka** [comment]
Not possible for the NVIDIA Shield TV.
