### ISSUE TITLE
App crash on schedule recording start/stop

### ISSUE THREAD

**Issue by tunip** [pipelka/roboTV#21]
Sometimes the roboTV app crashes ("roboTV wurde beendet") if a scheduled/instand recording starts or stops. Sometimes I see a toast on recording (no crash), sometime i see no toast on recording (no crash) and sometimes the app crash if a recording starts/stops.

**Comment by pipelka** [comment]
Please check if  version 0.5.1 fixes this problem:
https://github.com/pipelka/roboTV/releases/tag/v0.5.1

**Comment by tunip** [comment]
Yes, with 0.5.1 you fixed the issue. Many thx.

**Comment by tunip** [comment]
Another crash of the app after recording finished. First recording before was ok with no toast. Second recording finished 10 min. later and app crashed with no toast.

**Comment by pipelka** [comment]
Ok. New release, new luck:
https://github.com/pipelka/roboTV/releases/tag/v0.5.2

If the crash still happens for you please try to record a log with "adb logcat".

**Comment by tunip** [comment]
App is still crashing. Maybe we found the reason. It happens only if I record/delete a show without artwork/poster.

Output of "adb logcat" when app is chrashing:
09-25 16:12:31.715 25924 25969 E AndroidRuntime: FATAL EXCEPTION: Thread-209
09-25 16:12:31.715 25924 25969 E AndroidRuntime: Process: org.xvdr.robotv, PID: 25924
09-25 16:12:31.715 25924 25969 E AndroidRuntime: java.lang.IllegalArgumentException: Path must not be empty.
09-25 16:12:31.715 25924 25969 E AndroidRuntime:        at com.squareup.picasso.Picasso.load(Picasso.java:297)
09-25 16:12:31.715 25924 25969 E AndroidRuntime:        at org.xvdr.robotv.service.NotificationHandler$1.run(NotificationHandler.java:64)
09-25 16:12:31.715 25924 25969 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
09-25 16:12:31.754  1238  1238 E ApplicationPackageManager: android not found in CATEGORY_LEANBACK_LAUNCHER

**Comment by pipelka** [comment]
Ah, ok. That makes sense.

**Comment by tunip** [comment]
Looks better now :-). No crash with events without artwork.

**Comment by pipelka** [comment]
Alright. Closing.
