### ISSUE TITLE
cannot run my Project

### ISSUE THREAD

**Issue by Vapeelectronics** [pipelka/roboTV#25]
Error:A problem occurred configuring project ':app'.

> Could not find support-v4.jar (com.android.support:support-v4:24.0.0).
>   Searched in the following locations:
>       https://jcenter.bintray.com/com/android/support/support-v4/24.0.0/support-v4-24.0.0.jar

**Comment by pipelka** [comment]
Well, maybe you can't run your project but this is not from compiling roboTV. roboTV doesn't use the support-v4 library.
BTW, AndroidStudio prompts to install all the missing dependencies.

Maybe you have a bit more information for me, ...
