### ISSUE TITLE
App crash when timeshift is in use

### ISSUE THREAD

**Issue by tunip** [pipelka/roboTV#26]
Sometimes the app is crashing when timeshift is in use and I go to the beginning of the timeshift-buffer and fast-forward. If I jump to far in the timeshift-buffer i repeat it again (go to the timeshift beginning and fast-forward to the position I want).

Channel is a 1080i format. Will also try it with a 720p channel.

App log:
09-25 16:33:51.100 26127 26143 E AndroidRuntime: FATAL EXCEPTION: robotv:eventhandler
09-25 16:33:51.100 26127 26143 E AndroidRuntime: Process: org.xvdr.robotv, PID: 26127
09-25 16:33:51.100 26127 26143 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 73740 byte allocation with 17016 free bytes and 16KB until OOM
09-25 16:33:51.100 26127 26143 E AndroidRuntime:        at java.nio.ByteBuffer.allocate(ByteBuffer.java:56)
09-25 16:33:51.100 26127 26143 E AndroidRuntime:        at org.xvdr.extractor.SampleBuffer.resize(SampleBuffer.java:39)
09-25 16:33:51.100 26127 26143 E AndroidRuntime:        at org.xvdr.extractor.SampleBuffer.<init>(SampleBuffer.java:17)
09-25 16:33:51.100 26127 26143 E AndroidRuntime:        at org.xvdr.extractor.AdaptiveAllocator.<init>(AdaptiveAllocator.java:24)
09-25 16:33:51.100 26127 26143 E AndroidRuntime:        at org.xvdr.extractor.PacketQueue.<init>(PacketQueue.java:23)
09-25 16:33:51.100 26127 26143 E AndroidRuntime:        at org.xvdr.extractor.RoboTvSampleSource.<init>(RoboTvSampleSource.java:137)
09-25 16:33:51.100 26127 26143 E AndroidRuntime:        at org.xvdr.extractor.Player.open(Player.java:198)
09-25 16:33:51.100 26127 26143 E AndroidRuntime:        at org.xvdr.extractor.LiveTvPlayer.openStream(LiveTvPlayer.java:45)
09-25 16:33:51.100 26127 26143 E AndroidRuntime:        at org.xvdr.extractor.LiveTvPlayer.openStream(LiveTvPlayer.java:29)
09-25 16:33:51.100 26127 26143 E AndroidRuntime:        at org.xvdr.extractor.LiveTvPlayer.openStream(LiveTvPlayer.java:19)
09-25 16:33:51.100 26127 26143 E AndroidRuntime:        at org.xvdr.robotv.service.RoboTvSession.tune(RoboTvSession.java:352)
09-25 16:33:51.100 26127 26143 E AndroidRuntime:        at org.xvdr.robotv.service.RoboTvSession.access$000(RoboTvSession.java:35)
09-25 16:33:51.100 26127 26143 E AndroidRuntime:        at org.xvdr.robotv.service.RoboTvSession$TuneRunnable.run(RoboTvSession.java:60)
09-25 16:33:51.100 26127 26143 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:742)
09-25 16:33:51.100 26127 26143 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:97)
09-25 16:33:51.100 26127 26143 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
09-25 16:33:51.100 26127 26143 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:61)
09-25 16:33:51.100 26127 26143 E AndroidRuntime:        at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by pipelka** [comment]
The next version  0.6.0 will completely differ in handling timeshift as I'm currently implementing ExoPlayer2 (yes, I skipped my "own player" ambitions). ExoPlayer2 allows a much cleaner implementation of all the needed stuff.
Let's recheck this on the upcoming version, ...

**Comment by tunip** [comment]
Great news! Is rewinding then be possible in the timeshit buffer?

**Comment by pipelka** [comment]
The plan is to support all the timeshift features.
In trickplay mode (rewind, fast-forward, ...) the picture will be updated about every 500ms.

**Comment by tunip** [comment]
I am testing the exoplayer2 branch and it gets better and better. Great work 👍

**Comment by pipelka** [comment]
Is this still valid ?

**Comment by tunip** [comment]
Unfortunately yes, problem still exists with version 0.6. Need to get the log from the shield when i find time this week.
When I go backward/forward in the timeshift buffer and would go to the end of the buffer (live position) the blue circle flickers on the screen with no playback. If I press 2x backward shortly (for 1 sec.) it palys again.

During the Exoplayer V2 development I played a lot with the timeshift buffer and I was not able to crash the app. Hmmm

**Comment by pipelka** [comment]
Please retry with "master". There are some serious fixes.

**Comment by tunip** [comment]
Short test with "master" was fine. Will give more feedback in a few days. Thx

**Comment by tunip** [comment]
Longer tests are also fine. No crash anymore.

**Comment by pipelka** [comment]
Thanks for double checking. Time to close this issue.
