### ISSUE TITLE
DolbyDigital vs PCM

### ISSUE THREAD

**Issue by stevie1512** [pipelka/roboTV#32]
First of all many thanks for this great project. It made me change from tvheadend to vdr on my productive server again.
I have a question concerning surround sound. I am using the nvidia shield as streaming client. Release 0.6 is capable to make my AV receiver switch to DolbyDigital. Kodi 17(I think apart from SPMC) on the same machine makes it switching to PCM only. 
Unfortunately, when I compile the github sources robotv behaves as Kodi - the receiver switches to PCM.
What could be the reason ?

BR
Stefan

**Comment by tunip** [comment]
"Master" branch is newer then release 0.6. This means something changed from 0.6 to "Master".
Maybe it is the commit 2b3d8b2ad66b807fc41a2a6a370319b82243b7fd (ffmpeg is doing audio decoding now)

**Comment by pipelka** [comment]
You're right AC3 passthrough got lost somewhere.
Rescue mission initiated, ... 😆

**Comment by pipelka** [comment]
Please recheck with bb2fe1e941dfcbf2d61119a3afe8ee4111b93b5d

**Comment by stevie1512** [comment]
Great, I can confirm, it works again.
Thanks very much !

**Comment by pipelka** [comment]
Thanks for reporting the bug.

**Comment by hoppel118** [comment]
Hello Pipelka,

how do I get direct passthrough to work with robotv?

I only see pcm on my avr. My shield is configured the following way:

settings - hdmi - surround sound pass-through - on
settings - system - system sounds - off
robotv movies - settings - ac3 output - on

What else do I have to configure?

I am on version 0.6.0e69fb96?

Compiled this version of robotv with android studio yesterday. But I am competely new to android tv, android studio and robotv. Is this the latest version from git master branch or the latest stable version?

Direct passthrough works fine with other tools like "emby for android tv" and spmc.

Greetings Hoppel

**Comment by pipelka** [comment]
e69fb96fda352085f28a9a9024f661836c363697 ist the current head of "master". If AC3 output is on (in roboTV settings) all AC3 and E-AC3 streams will be streamed unmodified to your AVR. It work's for me and is confirmed in this thread. I don't know why it's not working for you. Maybe your selected audio track is not AC3 or E-AC3.

BTW, this issue is closed.
