### ISSUE TITLE
Feature request: Act as primary device

### ISSUE THREAD

**Issue by stevie1512** [pipelka/roboTV#33]
I thought it would be nice to get epg information via graphtftng. My server is headless with 4 dvb devices. In order to get graphtftng with an android display I have started vdr with 1 device + dummydevice + robotv + graphtftng but display information stays on first channel while switching. The idea was one vdr instance with one card, and another vdr instance with the remaining plugins and devices. 
Vnsiserver has an option called "d - act as primary device" which seems to make it possible to get graphtftng displaying the current streamed channel.
I am not sure if my idea makes sense for all scenarios but would it be possible to implement something so that graphtftng is showing info from current replayed robotv channel ?
Nothing important nice to have ....

**Comment by pipelka** [comment]
Completely useless for operation.
