### ISSUE TITLE
Featrue Request - Confirm channel switches by pressing "OK"

### ISSUE THREAD

**Issue by hoppel118** [pipelka/roboTV#34]
Hello pipelka,

first of all thanks for this amazing app. With some little features more it could replace kodi (spmc) the live tv function of kodi. For the movie library I use emby server and emby for android tv.

Is it somehow possible to get - Confirm channel switches by pressing "OK" - as an option. I like to scroll up and down before switching to the channel. It would be much smoother to zap through the program.

The same function works fine in kodi and is called: Confirm channel switches by pressing "OK".

Is this related to robotv or android live channels? Is it possible to get this in future?

Greetings hoppel

**Comment by pipelka** [comment]
I dont want to copy the k..i thing. I personally dislike this project for various reasons. If you want to browse channels before tuning just open the epg and switch from there. It much easier than that stupid confirmation.

**Comment by hoppel118** [comment]
Yes, you are right. The epg can also be used. But it's not a 1-click-zapping-method. You have to press "OK" twice and then choose the channel you want to watch. While it the requested way would be possible to go through the channels with the upper infobox and when you find a channel you want to zap in, you have to press "OK" once only.

This way you have a live tv picture the whole time and only while the one switch the picture is reloading.

It's not a priority thing, but I would be very happy to see this in a future version.

Greetings Hoppel
