### ISSUE TITLE
[Bug] Sometimes after channel change the picture hangs

### ISSUE THREAD

**Issue by tunip** [pipelka/roboTV#36]
Hi,

sometimes after a channel change (never seen this on 720p channel) the picture hangs, but audio is playing fine.
If I rewind shortly in the timeshift buffer it plays well. I also can then go back to live position in the timeshift buffer.
Apropos timeshit, it works very well now!

I use the latest git versions of the plugin and the app.

**Comment by stevie1512** [comment]
same here, especially when switching to DMAX HD (also on git)

**Comment by pipelka** [comment]
Please recheck with pipelka/vdr-plugin-robotv@9a923fc12fba83b3a218d29d3b5093a7eba49bd6

I did a lot of testing and it seems to be ok now, but this bug happens extremely rarely for me.

**Comment by stevie1512** [comment]
video freezing while switching to DMAX HD was happening very often on my system - with the changes I can not reproduce them anymore, so positive, seems to be fixed.

**Comment by tunip** [comment]
I did a lot of testing too. Looks fine now. Thx

**Comment by pipelka** [comment]
Great. Thanks for testing.
