### ISSUE TITLE
Timeshift 

### ISSUE THREAD

**Issue by stevie1512** [pipelka/roboTV#37]
With latest git sources, timeshift can't be switched off. The ringbuffer file is written, although timeshift is off.

**Comment by pipelka** [comment]
The ringbuffer is always used on the server. Switching timeshift off, disables the timeshift handling on Android TV.

**Comment by stevie1512** [comment]
ok. Would it be possible to make the ringbuffer file location configurable ?
I would rather put it on an SSD partition in order to allow the video hdd going to sleep.

**Comment by stevie1512** [comment]
Nevermind - I just saw it is already possible.
