### ISSUE TITLE
Wrong Aspect Ratio after updating to current gitmaster 

### ISSUE THREAD

**Issue by hoppel118** [pipelka/roboTV#38]
Hello pipelka,

today I updated to the newest version from gitmaster. 

After switching across this channel:

![img_2644](https://cloud.githubusercontent.com/assets/991344/21498938/985e70a8-cc31-11e6-8a5a-0a66c6495b20.JPG)

I get a wrong aspect ratio for all my other channels:

![img_2642](https://cloud.githubusercontent.com/assets/991344/21498937/985a6710-cc31-11e6-995c-b721e6a123bb.JPG)
![img_2643](https://cloud.githubusercontent.com/assets/991344/21498935/98569522-cc31-11e6-8d1b-7fa6fcfeed90.JPG)
![img_2645](https://cloud.githubusercontent.com/assets/991344/21498936/985a57e8-cc31-11e6-8200-59a22f6379b3.JPG)

This didn't happen in a sporadic manner. I restarted my shield 3 times and always had the same error after switching across the channel "kabel eins". The aspect ratio from "kabel eins" seems to differ from others channels. It has a black frame around the complete live tv picture.

Do you need any further information? Where do I find roboTV-logfiles on the shield? 

Thias may have to do with this changes: https://github.com/pipelka/roboTV/issues/31 

Greetings Hoppel

**Comment by pipelka** [comment]
Looks like #31.
The solution was to update to the latest version of the "Live Channels" app.

Logs from the Shield can be pulled like on any other Android device via:
<pre>
# adb logcat
</pre>

The interesting part would be from switching to startup of the channel.

**Comment by s0faking** [comment]
just experienced the same thing using the latest master commits. its looks like the player gets confused when switching from a 4:3 source back to 16:9 content. 
[aspect.txt](https://github.com/pipelka/roboTV/files/674200/aspect.txt)

**Comment by pipelka** [comment]
Alright. That was the right hint. Switching from 4:3 to 16:9 causes this. To me it seems the 4:3 picture is already distorted. I think I'll revert the changes made for #31 as something else was causing the problem.

**Comment by pipelka** [comment]
Please recheck with 243496e5bfea345781c4e302f69df3bbbf19a7a7

**Comment by hoppel118** [comment]
Zapped through my first 50 channels up and down. I didn't have the issue with the wrong aspect ratio again.

Well done!

Keep up the good work, I really appreciate it!

Greetings Hoppel

**Comment by s0faking** [comment]
works for me as well. thx @pipelka

**Comment by pipelka** [comment]
Thanks for testing.
