### ISSUE TITLE
Dolby Digital still doesn't work

### ISSUE THREAD

**Issue by hoppel118** [pipelka/roboTV#39]
Hello Alexander,

today I compiled the versions from gitmaster for the vdr plugin and the roboTV app.

I still do not see dolby digital working. With this version I don't see "PCM" anymore, like with the app version before, but I also don't see "Dolby Digital" on the display of my avr.

My avr shows me the "ProLogic II Movie" audio format. With vnsi and spmc I can see the "Dolby Digital" audio format for the same channels (for example RTL, PRO7, ARD, ZDF).

It must have something to do with the changes made here: https://github.com/pipelka/roboTV/issues/32

Do you need any further information? Where do I find the roboTV logfile on the nvidia shield tv? 

Greetings Hoppel

**Comment by pipelka** [comment]
Neither I know why your AVR displays that nor do I know what other projects do.
I know that (E)AC3 streams are passed through to your AVR if enabled (at least it does that for me and for some others).
If you're unable to change the volume level with your shield remote then passthrough is enabled.
Before #32 passthrough did NOT work.

**Comment by hoppel118** [comment]
ok, thanks for explaining. Didn't know that it didn't work before https://github.com/pipelka/roboTV/issues/32 because I didn't use roboTV before this.

If I configure the settings in one of the following constellations, I can't hear audio anymore :
- android settings - hdmi - surround sound pass-through - off | on
- android settings - system - system sounds - off
- android settings - system - volume modus - variable | fix
- robotv movies - settings - ac3 output - off | on

Only if I configure my system with the following settings and use "cec" to control the volume of my avr I see the "ProLogic II Movie" and hear sound:
- android settings - hdmi - surround sound pass-through - on
- android settings - system - system sounds - off
- android settings - system - volume modus - cec
- robotv movies - settings - ac3 output - on

I can't give you more information at the moment. First I have to find out how "adb logcat" works.

Thanks and greetings Hoppel

**Comment by pipelka** [comment]
To be honest I don't know why you are thinking that DD does not work.
Everything seems to be ok for me. Please check which audio track is selected for your channel.
It should be a "5.1 surround" channel.

**Comment by hoppel118** [comment]
Ahh...., ok. Thanks for this hint. That did the trick! How I said, I am new to the android tv world. ;)

Is it somehow possible that roboTV chooses the best available audio format as a default setting?

Thank you very much!

**Comment by pipelka** [comment]
It should prefer AC3 but remembers the last choice.
I'll take a look at this.

**Comment by hoppel118** [comment]
It remembers the choice for the last channel only.

Thanks!
