### ISSUE TITLE
Not an Issue - only a question - How is it possible to "stop" live channel?

### ISSUE THREAD

**Issue by hoppel118** [pipelka/roboTV#40]
Hello Alexander,

I have an nvidia shield tv with the nvidia remote. I am on the way to get ready for a life without kodi/spmc. For this I need two apps working. One of these apps is roboTV (the other app is emby).

How is it possible to stop live channel viewing without starting another ap? I can't find a "stop" button under "Wiedergabesteuerung".

Thanks in advance!

Greetings Hoppel

**Comment by pipelka** [comment]
It's not directly possible. Android TV closes live channels only by switching to a different app or when suspended.

**Comment by hoppel118** [comment]
OK, thanks for this information.
