### ISSUE TITLE
No EPG/Program Info

### ISSUE THREAD

**Issue by reinhard-brandstaedter** [pipelka/roboTV#41]
Since I updated to v0.6.0 and the VDP plugin to 0.9.102 I'm not seeing any EPG Program information anymore.
I checked/deleted vdr/cache/epg.data and it seems to be fine with accurate information, not displayed in the app though.

Any ideas?

**Comment by pipelka** [comment]
v0.6.0 was an awefully broken release (tons of changes, tons of bugs).
I'm currently preparing v0.6.1. You should use the git "master" versions (client and vdr plugin) or wait for v0.6.1 (about to be released this week).

**Comment by reinhard-brandstaedter** [comment]
Oh thanks for the info will wait for 0.6.1, not a problem!
I'm currently only building the vdr plugin myself and haven't gone through the exercise for an android build environment...so happy to wait for the release.

**Comment by tunip** [comment]
@reinhard-brandstaedter you could use this link for the app if you want to test it (Latest commit 9ce5b4b):
https://www.dropbox.com/s/v282650zcmxbz92/robotv-debug.apk?dl=0

**Comment by pipelka** [comment]
The build bot just finished deploying the release:
https://github.com/pipelka/roboTV/releases/tag/v0.6.1

Please (re)import your channels after updating.

**Comment by reinhard-brandstaedter** [comment]
I tried the latest release and the EPG information still doesn't show up after refreshing channels. I also tried clearing caches and data. Strange

**Comment by pipelka** [comment]
Was there any crash (notification that roboTV died) after importing the channel list ?

Usually EPG sync takes a couple of minutes (depending on your number of channels) and starts after importing channel data. There won't be any EPG entries immediately after import.

**Comment by reinhard-brandstaedter** [comment]
I went back checking today, channels and EPG are working now. I was a bit too unpatient.
0.6.1 is working stable now! Thank you, great job. Love it!
