### ISSUE TITLE
[Feature] Remove season/episode information from description/episodetitle

### ISSUE THREAD

**Issue by tunip** [pipelka/roboTV#42]
Small feature request. Cut out season & episode information e.g. `4. Staffel, Folge 4: ` from description if COLUMN_SEASON_DISPLAY_NUMBER and/or COLUMN_EPISODE_DISPLAY_NUMBER is Set  and episode information e.g. `, Folge 53` from episodetitle (subtitle).

**Comment by pipelka** [comment]
Agreed. Thats really annoying.
I'm currently a bit busy. PR's fixing this are highly welcome.

**Comment by pipelka** [comment]
Ok. Easier than I thought, ...
