### ISSUE TITLE
yaVDR 0.6.1 VDR 2.2.0 wont work

### ISSUE THREAD

**Issue by frankdoo** [pipelka/roboTV#43]
Dear pipelka, first of all nice work thank you for that!

I try to make the "Version 0.11.0-vdr-2.2.x" for my yaVDR. It work no error "libvdr-robotv.so.2.2.0" and make install. I run vdr and I got:

>loading plugin: /usr/lib/vdr/plugins/libvdr-robotv.so.2.2.0
> ERROR: /usr/lib/vdr/plugins/libvdr-robotv.so.2.2.0: undefined symbol: _ZNSt20regex_token_iteratorIN9__gnu_cxx17__normal_iteratorIPKcSsEEcSt12regex_traitsIcEEneERKS7_
>

Any idea what that is? 

Plugins so far:
vdr (2.2.0/2.2.0) - The Video Disk Recorder, wirbelscan (0.0.9) - DVB and pvrinput channel scan for VDR, dbus2vdr (31) - control vdr via D-Bus, dvbsddevice (2.2.0) - SD Full Featured DVB device, femon (2.2.2) - DVB Signal Information Monitor (OSD), markad (0.1.5pre) - Mark advertisements, iptv (2.2.1) - Experience the IPTV, remoteosd (1.0.0) - Show menu of a remote VDR, osdserver (0.1.3) - Server for remote OSD clients, menuorg (0.5.1) - Reorganizes the main menu, epgsearch (1.0.1.beta5) - search the EPG for repeats and more, channellists (0.0.5) - Manage your channellists, quickepgsearch (0.0.1) - Quick search for broadcasts,

**Comment by pipelka** [comment]
I'm sorry. VDR 2.2.0 isn't supported anymore.
It was simply too much work to backport all the changes and maintain 2 branches of the plugin.
Maybe it's possible to run an older version of the plugin for VDR 2.2.0 but it won't support the latest roboTV version.

In your case it might be some compiler issue.

**Comment by frankdoo** [comment]
Thanks - I update my system.

**Comment by frankdoo** [comment]
Now I change to EasyVDR with the mango repository and install 2.3.8 plugin compiled. Works - No Error on startup. Only that I understand this - with the vdr-plugin I don't need the docker-robotv-server?

**Comment by pipelka** [comment]
The docker container is a all in one package running vdr and all required plugins. It's turnkey solution replacing the local vdr installation.
