### ISSUE TITLE
(Sony TV) Error when streaming some channels // Audio rendering & initialization fails

### ISSUE THREAD

**Issue by Jondalar** [pipelka/roboTV#44]
Hi,

I recently bought a SonyTV and got roboTV running easily with the info & docker provided here. 

Some channels don't play on the SonyTV though (they do in Android Studio and very occasionally the application also plays them on the TV).

Here is some debug output I traced with adb connected:

`02-03 15:41:44.360 7841-7841/org.xvdr.robotv I/TVSession: onTune: content://android.media.tv/channel/2707
02-03 15:41:44.824 7841-7841/org.xvdr.robotv D/Player: open sync: robotv://livetv/2052563304
02-03 15:41:44.903 7841-9290/org.xvdr.robotv D/MtkACodecPlugin: MtkACodecPlugin destoryAPlugin
02-03 15:41:44.907 7841-9284/org.xvdr.robotv D/org.robotv.player.source.RoboTvDataSource: close
02-03 15:41:44.909 7841-9342/org.xvdr.robotv D/org.robotv.player.source.RoboTvDataSource: open: robotv://livetv/2052563304
02-03 15:41:44.909 7841-9342/org.xvdr.robotv D/org.robotv.player.source.RoboTvDataSource: start streaming: robotv://livetv/2052563304
02-03 15:41:44.945 7841-8336/org.xvdr.robotv D/ChannelSyncAdapter: importing EPG of channel 335
02-03 15:41:44.959 7841-8336/org.xvdr.robotv D/org.robotv.sync.SyncUtils: Fetching new EPG entries for channel 335 - Kinowelt TV
02-03 15:41:45.017 7841-9342/org.xvdr.robotv D/org.robotv.player.source.RoboTvDataSource: live stream opened
02-03 15:41:45.018 7841-7841/org.xvdr.robotv D/Player: open sync - done
02-03 15:41:45.018 7841-7841/org.xvdr.robotv I/TVSession: successfully switched channel
02-03 15:41:45.018 7841-7841/org.xvdr.robotv I/Player: onPlayerStateChanged true 1
02-03 15:41:45.018 7841-7841/org.xvdr.robotv I/Player: onPlayerStateChanged true 2
02-03 15:41:45.019 7841-9342/org.xvdr.robotv D/org.robotv.player.extractor.RoboTvExtractor: seek: 0
02-03 15:41:45.574 7841-8336/org.xvdr.robotv D/ChannelSyncAdapter: importing EPG of channel 336
02-03 15:41:45.583 7841-8336/org.xvdr.robotv D/org.robotv.sync.SyncUtils: Fetching new EPG entries for channel 336 - AXN Action
02-03 15:41:46.333 7841-8336/org.xvdr.robotv D/ChannelSyncAdapter: importing EPG of channel 337
02-03 15:41:46.354 7841-8336/org.xvdr.robotv D/org.robotv.sync.SyncUtils: Fetching new EPG entries for channel 337 - Gute Laune TV
02-03 15:41:47.100 7841-8336/org.xvdr.robotv D/ChannelSyncAdapter: importing EPG of channel 338
02-03 15:41:47.149 7841-8336/org.xvdr.robotv D/org.robotv.sync.SyncUtils: Fetching new EPG entries for channel 338 - kabel eins classics
02-03 15:41:47.188 7841-9342/org.xvdr.robotv D/org.robotv.player.extractor.RoboTvExtractor: stream change packet received
02-03 15:41:47.188 7841-9342/org.xvdr.robotv D/StreamBundle: new streamchange: 3 entries
02-03 15:41:47.189 7841-9342/org.xvdr.robotv D/StreamBundle: stream: 0
02-03 15:41:47.189 7841-9342/org.xvdr.robotv D/StreamBundle: type: H264
02-03 15:41:47.189 7841-9342/org.xvdr.robotv I/StreamBundle: new 2 H264 stream (1279)
02-03 15:41:47.189 7841-9342/org.xvdr.robotv D/StreamBundle: stream: 1
02-03 15:41:47.189 7841-9342/org.xvdr.robotv D/StreamBundle: type: AC3
02-03 15:41:47.189 7841-9342/org.xvdr.robotv I/StreamBundle: new 1 AC3 stream (1283)
02-03 15:41:47.189 7841-9342/org.xvdr.robotv D/StreamBundle: stream: 2
02-03 15:41:47.189 7841-9342/org.xvdr.robotv D/StreamBundle: type: AC3
02-03 15:41:47.189 7841-9342/org.xvdr.robotv I/StreamBundle: new 1 AC3 stream (1284)
02-03 15:41:47.189 7841-9342/org.xvdr.robotv D/org.robotv.player.extractor.RoboTvExtractor: create streams
02-03 15:41:47.189 7841-9342/org.xvdr.robotv I/StreamManager: video track pid: 1279
02-03 15:41:47.190 7841-9342/org.xvdr.robotv I/StreamManager: audio track pid: 1283
02-03 15:41:47.190 7841-9342/org.xvdr.robotv I/TrackInfoMapper: native size: 1920x1080
02-03 15:41:47.190 7841-9342/org.xvdr.robotv I/TrackInfoMapper: pixel aspect ratio: 1.0
02-03 15:41:47.190 7841-9342/org.xvdr.robotv I/TrackInfoMapper: video size: 1920x1080
02-03 15:41:47.190 7841-9342/org.xvdr.robotv D/TVSession: onAudioTrackChanged: 1283
02-03 15:41:47.190 7841-9342/org.xvdr.robotv D/org.robotv.player.extractor.RoboTvExtractor: skipping 216 bytes (stream change packet)
02-03 15:41:47.193 7841-7841/org.xvdr.robotv D/TVSession: onAudioTrackChanged: 1283
02-03 15:41:47.225 7841-9176/org.xvdr.robotv D/MtkACodecPlugin: MtkACodecPlugin createAPlugin
02-03 15:41:47.239 7841-9349/org.xvdr.robotv I/OMXClient: MuxOMX ctor
02-03 15:41:47.240 7841-9349/org.xvdr.robotv D/MtkACodecPlugin: OMX.MTK.VIDEO.DECODER.AVC needRmClient (597)
02-03 15:41:47.241 7841-9349/org.xvdr.robotv D/MtkACodecPlugin: OMX.MTK.VIDEO.DECODER.AVC mNeedVdpImgrz (603)
02-03 15:41:47.285 7841-9348/org.xvdr.robotv I/MediaCodec: [OMX.MTK.VIDEO.DECODER.AVC] setting surface generation to 8029210
02-03 15:41:47.288 7841-9348/org.xvdr.robotv D/MtkMediaCodecPlugin: [OMX.MTK.VIDEO.DECODER.AVC] set mOutputPath = 0 L(150)
02-03 15:41:47.297 7841-9349/org.xvdr.robotv D/MtkACodecPlugin: tunneledplayback, set mOutputPath = OUTPUT_VIDEO_MAIN
02-03 15:41:47.303 7841-9349/org.xvdr.robotv D/binder.hwcomposer: [enable_vdp:59] ENABLE_VDP ok
02-03 15:41:47.303 7841-9349/org.xvdr.robotv I/ACodec: Configuring TUNNELED video playback.
02-03 15:41:47.340 7841-9349/org.xvdr.robotv D/MtkACodecPlugin: add usage GRALLOC_USAGE_PATH_VDP0
02-03 15:41:47.344 7841-9349/org.xvdr.robotv D/SurfaceUtils: set up nativeWindow 0x90279708 for 1920x1080, color 0x103, rotation 0, usage 0x30002900
02-03 15:41:47.370 7841-9176/org.xvdr.robotv E/AudioTrack: Could not get audio output for session 89, stream type -1, usage 1, sample rate 48000, format 0x1, channel mask 0x3f, flags 0x41
02-03 15:41:47.370 7841-9176/org.xvdr.robotv E/AudioTrack-JNI: Error -22 initializing AudioTrack
02-03 15:41:47.370 7841-9176/org.xvdr.robotv E/android.media.AudioTrack: Error code -20 when initializing AudioTrack.
02-03 15:41:47.372 7841-9176/org.xvdr.robotv E/ExoPlayerImplInternal: Renderer error.
                                                                      com.google.android.exoplayer2.ExoPlaybackException
                                                                          at com.google.android.exoplayer2.audio.SimpleDecoderAudioRenderer.render(SimpleDecoderAudioRenderer.java:255)
                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560)
                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                       Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(48000, 252, 144000)
                                                                          at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:1180)
                                                                          at com.google.android.exoplayer2.audio.DefaultAudioSink.initialize(DefaultAudioSink.java:487)
                                                                          at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:544)
                                                                          at com.google.android.exoplayer2.audio.SimpleDecoderAudioRenderer.drainOutputBuffer(SimpleDecoderAudioRenderer.java:347)
                                                                          at com.google.android.exoplayer2.audio.SimpleDecoderAudioRenderer.render(SimpleDecoderAudioRenderer.java:250)
                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560) 
                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                          at android.os.Looper.loop(Looper.java:154) 
                                                                          at android.os.HandlerThread.run(HandlerThread.java:61) 
02-03 15:41:47.375 7841-7841/org.xvdr.robotv E/TVSession: onPlayerError
02-03 15:41:47.375 7841-7841/org.xvdr.robotv W/System.err: com.google.android.exoplayer2.ExoPlaybackException
02-03 15:41:47.375 7841-7841/org.xvdr.robotv W/System.err:     at com.google.android.exoplayer2.audio.SimpleDecoderAudioRenderer.render(SimpleDecoderAudioRenderer.java:255)
02-03 15:41:47.375 7841-7841/org.xvdr.robotv W/System.err:     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560)
02-03 15:41:47.376 7841-7841/org.xvdr.robotv W/System.err:     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306)
02-03 15:41:47.376 7841-7841/org.xvdr.robotv W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
02-03 15:41:47.376 7841-7841/org.xvdr.robotv W/System.err:     at android.os.Looper.loop(Looper.java:154)
02-03 15:41:47.376 7841-7841/org.xvdr.robotv W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
02-03 15:41:47.376 7841-7841/org.xvdr.robotv W/System.err: Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(48000, 252, 144000)
02-03 15:41:47.376 7841-7841/org.xvdr.robotv W/System.err:     at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:1180)
02-03 15:41:47.376 7841-7841/org.xvdr.robotv W/System.err:     at com.google.android.exoplayer2.audio.DefaultAudioSink.initialize(DefaultAudioSink.java:487)
02-03 15:41:47.376 7841-7841/org.xvdr.robotv W/System.err:     at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:544)
02-03 15:41:47.376 7841-7841/org.xvdr.robotv W/System.err:     at com.google.android.exoplayer2.audio.SimpleDecoderAudioRenderer.drainOutputBuffer(SimpleDecoderAudioRenderer.java:347)
02-03 15:41:47.376 7841-7841/org.xvdr.robotv W/System.err:     at com.google.android.exoplayer2.audio.SimpleDecoderAudioRenderer.render(SimpleDecoderAudioRenderer.java:250)
02-03 15:41:47.376 7841-7841/org.xvdr.robotv W/System.err: 	... 5 more
02-03 15:41:47.376 7841-7841/org.xvdr.robotv D/NotificationHandler: notify: Wiedergabefehler / Fehler
02-03 15:41:47.435 7841-9348/org.xvdr.robotv D/MtkACodecPlugin: MtkACodecPlugin destoryAPlugin
02-03 15:41:47.446 7841-7841/org.xvdr.robotv I/Player: onPlayerStateChanged true 1
02-03 15:41:47.447 7841-7869/org.xvdr.robotv D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
02-03 15:41:47.820 7841-9342/org.xvdr.robotv D/org.robotv.player.source.RoboTvDataSource: close`

Is there a way to look deeper into this?  Happy to run test builds.

Cheers
Alex

**Comment by pipelka** [comment]
The log is a bit hard to read but I see there's an AC3 audio stream.
As a first shot could you try to enable AC3 passthrough (in the roboTV settings).

**Comment by pipelka** [comment]
Ahh,.. forgot to ask:
Which roboTV version are you using (prebuilt apk / git master) ?

**Comment by Jondalar** [comment]
Using 0.7.3.cfeb528, built as debug with android studio.

Where is the AC3 pass through param, in the android app or the vdr-plugin ?

**Comment by pipelka** [comment]
Ok. Your building the current master. Good.

AC3 passthrough can be enabled in the input source settings (where you
imported your channel list) of the Live Channels app.
If AC3 passthrough isn't supported there won't be an option for that.

Am 04.02.2018 10:37 schrieb "Alex Damhuis" <notifications@github.com>:

**Comment by Jondalar** [comment]
I think I got the item in the settings ... ("Einstellungen") when I enter the Streaming settings. It fails to open though ("es ist ein unerwarteter Fehler aufgetreten" / an unexpected error occurred). There is no Debugoutput also, so I assume the error happens in the SONY UI.

Can I set the default to TRUE for passthrough somewhere?

**Comment by Jondalar** [comment]
When connecting ADB and looking at all output, here is what happens when pressing the Settings Button: https://pastebin.com/BhQAW9gd

`02-04 11:52:39.676 1752-3353/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cmp=org.xvdr.robotv/org.robotv.setup.SettingsActivity (has extras)} from uid 10061 on display 0
02-04 11:52:39.677 27743-27743/? W/System.err: android.content.ActivityNotFoundException: Unable to find explicit activity class {org.xvdr.robotv/org.robotv.setup.SettingsActivity}; have you declared this activity in your AndroidManifest.xml?`

**Comment by pipelka** [comment]
This interface doesn't exists anymore (was part of an early specification).
Is there a firmware update for you TV.
BTW, which Android TV version is on your TV.

AC3 settings can also be altered in the "roboTV Movies" app.

**Comment by Jondalar** [comment]
I added screenshots (fotos). The Settingsoption from Movies leads to the reduced Settings Menu and on my TV there is no Submenu with options around sound/AC3 that I can see unfortunately.

The Version is BRAVIA_ATV2_EU-user 7.0 NRD91N.S90 1.6.0.26.71.1.00

On the attached pictures:

0 = SonyTV Info page
![0_sony_androidtv](https://user-images.githubusercontent.com/682272/35794153-e7c4342c-0a54-11e8-8059-7738271b2812.jpg)

1+2 = Trying to find the settings when coming from Movies App
![1_filme_einstellungen](https://user-images.githubusercontent.com/682272/35794152-e7adc778-0a54-11e8-9bae-7f38f8b37166.jpg)
![2_einstellungen](https://user-images.githubusercontent.com/682272/35794171-f647a42a-0a54-11e8-9210-321be4887ff2.jpg)

3-5 = How settings show up when using the ATV Settings->Channels->Streaming Channels sections
![3_settings_streaming](https://user-images.githubusercontent.com/682272/35794182-043ccbaa-0a55-11e8-9c7a-f007398b047a.jpg)
![4_settings_robotv](https://user-images.githubusercontent.com/682272/35794188-0ac80048-0a55-11e8-8cf6-1288e7cf59a1.jpg)
![5_settings_error](https://user-images.githubusercontent.com/682272/35794198-140a4044-0a55-11e8-8cce-b1a20de00ad1.jpg)

**Comment by pipelka** [comment]
Thanks. I understand now.
It's strange that the "Settings" interface is still present while not being in the Android TV documentation, ...
It's also strange that AC3 passthrough seems to be unsupported.

Do always the same channels show the audio problem or is it just accidentally happening on all channels ?
Does is also happen with MPEG audio tracks or only with AC3 tracks ?

To further analyze the problem a readable log from the TV and the corresponding log from the VDR server is needed.

**Comment by Jondalar** [comment]
On Ac3 - with the TVH live channel I can activate the AC3 passthrough, at least they have the options and the channels impacted worked when trying.

It happens "occasionally", but most of the time with SKY HD channels. I also experienced it that one movie works and then, when the next one comes up the error occurs (when they change the stream).

I created a file, which is attached, with ADB showing the error on the TV.

For VDR I currently run your docker (set to VDR-log-level = 3), but the only output logged to the console is: 

vdr: no fonts available - OSD will not show any text!   

Is the container logging into somewhere else (a file) ? If not, I will have to see that I set up a VDR installation manually with access to syslog.

ADB output.
[robotv_error.txt](https://github.com/pipelka/roboTV/files/1694571/robotv_error.txt)

**Comment by Jondalar** [comment]
Additional question - is there a way that I can tweak the code so passthrough-support is activated by code. That would be a way to validate the theory if this is the cause. The menu is a separate issue, right ? :-)

**Comment by pipelka** [comment]
To force AC3 passthrough you may set this to "true":
https://github.com/pipelka/roboTV/blob/cfeb528ecc536471ff7faff11ccc10309cdc9f59/robotv-player/src/main/java/org/robotv/player/Player.java#L99

**Comment by Jondalar** [comment]
Thanks Alexander, I tried but the issues stays... Strange. Anything else I can do on my end?

**Comment by pipelka** [comment]
Please show me the log with the "forced" AC3 passthrough output.
You could try an older prebuilt roboTV version (0.7.3) which use an older ExoPlayer version.

**Comment by Jondalar** [comment]
I attached the log when it sits on true... I also tried to query audioCapabilities.supportsEncoding(AudioFormat.ENCODING_AC3) and it returned a false. Which is strange, but it seems that Nougat and Sony do not really work well if it comes to passthrough :-(

However, the good news is with roboTV 0.6.3 it works. I assume you changed to a newer version of Exoplayer for 0.7.x, did you ?

If you want me to run patches and/custom debug code to create logs, I am more than happy to!

[073_robotv_SONY_error_passthrough_true.txt](https://github.com/pipelka/roboTV/files/1695434/073_robotv_SONY_error_passthrough_true.txt)

**Comment by pipelka** [comment]
From the log I see that the passthrough mode wasn't really enabled (it just reported to do so).
I'll do some changes to really force the passthrough mode (and maybe add a workaround for Sony TV's).

Version 0.6.3 uses the ancient ExoPlayer 2.1.1. Does the audiotrack work with or without AC3 passthrough enabled ?

**Comment by Jondalar** [comment]
I can not say honestly, as the options are not accessible in my UI. Sure, let me know when you have something to compile ready. 

0.6.3 is working well, it just takes 2-3 times longer to switch channels compared to 0.7.x

**Comment by Jondalar** [comment]
Addon - do you want me to get a debug log for 0.6.3 ?

**Comment by pipelka** [comment]
Would be helpful to see which audiotracks / modes being used.
Yes. Please.

**Comment by pipelka** [comment]
Another try:
0.6.3 didn't support the video tunnel playback option. Maybe that is causing the problem.

Please comment this line:
https://github.com/pipelka/roboTV/blob/cfeb528ecc536471ff7faff11ccc10309cdc9f59/robotv-player/src/main/java/org/robotv/player/Player.java#L110

**Comment by Jondalar** [comment]
A log for 0.6.3 is here. It is much less "talkative", is this enough or do you want me to build a specific commit/tag and instan-run this via AndroidStudio to take logs?

[robotTV_0.6.3_adb_log_SonyTV.txt](https://github.com/pipelka/roboTV/files/1695692/robotTV_0.6.3_adb_log_SonyTV.txt)

**Comment by Jondalar** [comment]
I can confirm that commenting out of the tunnel playback option did the trick. 

Running a current build of master with just the // infront of the line you sent me and it works.

**Comment by Jondalar** [comment]
Just experimenting - why not do it like this:

`if (passthrough) {
           
           trackSelector.setTunnelingAudioSessionId(C.generateAudioSessionIdV21(context));

        };`

So when the passthrough is not working or in use, do not use the tunneling ? This way it is device independent...

**Comment by KaiKrause** [comment]
Hello,
since I have the same problem on my SonyTV I did try to create the package on myselfe.

I can confirm that the latest master works with my SonyTV. I did get the option to deactivate tunneling playback.

Kai

**Comment by SebJohann** [comment]
Hi together,
I have the same issue with my Sony Android TV - only Channels with 2ch Audio are working.
I tried to make a APK from the up2date git sources, but it ran into some errors - it weas the first time I tried to compile a APK. Is it possible to have an updates APK with the "Sony Fix" in it?

Thanks a lot
Seb

**Comment by Jondalar** [comment]
Hi Seb, 

no sure if this is helping you - but I attached my last build that I made locally for myself. Give that one a try. 

@pipelka - I had tried the last release under Oreo after Sony updated, but the pass through options still do not show up. Seems they have made some kind of changed to the standard inside the Sony version of atv. 

If you do not want the binary here, please let me know and I will delete.

[robotv-0.7.3-debug.apk.zip](https://github.com/pipelka/roboTV/files/3099816/robotv-0.7.3-debug.apk.zip)

Cheers
A

**Comment by pipelka** [comment]
Fixed a long time ago.
Check out the latest release 0.9.0.
