### ISSUE TITLE
Stream does not Start

### ISSUE THREAD

**Issue by TheChief79** [pipelka/roboTV#45]
I have a problem with Live Streaming from vdr-2.3.8, robotv-plugin (git) and APK 0.7.3. Live Streaming isnt working at the moment. The VDR Log file says:

> Feb  6 17:27:52 homeserver vdr: [11172] CHANNEL STREAM REQUEST
> Feb  6 17:27:52 homeserver vdr: [11172] ======================================
> Feb  6 17:27:52 homeserver vdr: [11172] 3 - MDR Thüringen HD (S19.2E-1-1061-10354)
> Feb  6 17:27:52 homeserver vdr: [11172] --------------------------------------
> Feb  6 17:27:52 homeserver vdr: [11173] device 1 receiver thread ended (pid=10625, tid=11173)
> Feb  6 17:27:52 homeserver vdr: [11172] LiveQueue terminated
> Feb  6 17:27:52 homeserver vdr: [11172] live streamer terminated
> Feb  6 17:27:52 homeserver vdr: [11172] Found available device 1
> Feb  6 17:27:52 homeserver vdr: [11172] adding channel to cache
> Feb  6 17:27:52 homeserver vdr: [11172] Creating demuxers
> Feb  6 17:27:52 homeserver vdr: [11172] Successfully switched to channel 3 - MDR Thüringen HD
> Feb  6 17:27:52 homeserver vdr: [11172] done switching.
> Feb  6 17:27:52 homeserver vdr: [11179] device 1 receiver thread started (pid=10625, tid=11179, prio=high)
> Feb  6 17:27:52 homeserver vdr: [11172] --------------------------------------
> Feb  6 17:27:52 homeserver vdr: [11172] Started streaming of channel MDR Thüringen HD (priority 50)
> Feb  6 17:27:53 homeserver vdr: [11179] demuxers ready
> Feb  6 17:27:53 homeserver vdr: [11179] Stream: H264 PID: 5331 1280x720 DAR: 1,78 FPS: 50,000 SPS/PPS/VPS: 20/15/0 bytes (parsed: yes)
> Feb  6 17:27:53 homeserver vdr: [11179] Stream: AC3 PID: 5336 48000 Hz, 2 channels, Lang: deu (parsed: yes)
> Feb  6 17:27:53 homeserver vdr: [11179] Stream: MPEG2AUDIO PID: 5332 48000 Hz, 2 channels, Lang: deu (parsed: yes)
> Feb  6 17:27:53 homeserver vdr: [11179] Stream: MPEG2AUDIO PID: 5333 48000 Hz, 2 channels, Lang: mis (parsed: yes)
> Feb  6 17:27:53 homeserver vdr: [11179] Stream: DVBSUB PID: 5335 Lang: deu (parsed: yes)
> Feb  6 17:27:53 homeserver vdr: [11179] processing 42 pre-queued packets
> Feb  6 17:27:53 homeserver vdr: [11181] timeshift file: /volume1/vdr/robotv-ringbuffer-00049.data

Any ideas?

I one case i got video, after i did something different for an half hour.

Recordings from Server are working.

**Comment by TheChief79** [comment]
After i set the timeshift file to 100MB, i can stream channels. Why is it needed, if timeshift in ATV is disabled? Dont want to write permanently to the server disk. Is it not possible to stream without that file?

**Comment by pipelka** [comment]
The timeshift file is needed because I need it (it's a fundamental part of how the system works).
No it's not possible to stream without that file.
But it's possible to put the timeshift files on a ram disk to avoid disk activity.
