### ISSUE TITLE
FireTV Compatibility?

### ISSUE THREAD

**Issue by henfri** [pipelka/roboTV#46]
Hello,

roboTV looks great. I'd really like to use it. 
Will it run on an Amazon FireTV?

Regards,
Hendrik

**Comment by Moorviper** [comment]
ähm 
https://www.vdr-portal.de/forum/index.php?thread/131544-robotv-vdr-client-auf-android-tv/&postID=1301909#post1301909

you still got your answer and a bugtracker is not a support platform.

This is not a issue.

**Comment by pipelka** [comment]
Nevertheless I'm thinking about it ;-)

The roboTV Movies app should work on FireTV but I don't know if it will be presented on the main screen. Searching by speech recognition will also not work (Amazon's speech recognition isn't integrated into the Google API's).

LiveTV will currently not work. But with the recent structural changes the chances of implementing a plain Android LiveTV app got much better.

**Comment by henfri** [comment]
Thanks for your replies.
@Daniel: The answer from your link is only partially correct then and also I am not sure Alexander reads the german discussion. 

@Alexander: Thanks for giving me hope. I will test roboTV on FireTV then. I would be really thrilled if you made LiveTV working, but I also understand if you have other priorities.

Greetings,
Hendrik

**Comment by henfri** [comment]
Hello,
do you still consider this?
I am not really happy with Kodi on my firetv...

Greetings,
Hendrik

**Comment by pipelka** [comment]
I just threw my FireTV stick out of the window. Do expect it to be supported.
