### ISSUE TITLE
Feature request: Send WOL packet

### ISSUE THREAD

**Issue by KaiKrause** [pipelka/roboTV#47]
Hi,

would it be possible to add support for sending a WOL packet to wake up the VDR server?

Since not all server support native WOL (like ARM hardware), it would be nice to be able to configure a different IP address. Then you can build a small arduino with ethernet shield to listen to the packet. Or an existing server may wake the VDR via GPIO.

**Comment by pipelka** [comment]
Out of scope. I think this is not in the responsibility of the VDR plugin.
