### ISSUE TITLE
Anyway to enable an EXT remux script for remote clients?

### ISSUE THREAD

**Issue by mattgorski** [pipelka/roboTV#48]
I have been following your work for years pipelka and stumbled across your github looking for the old xvdr and to my surprise after years of using Android TV with tvheadend (VDR user since 2006) i discovered your awesome frontend app and backend vdr plugin.

As the heading says just curious if there is anyway to use an EXT script for encoding channels.  I use nvenc on linux and prefer H264 channels over MPEG2 in Android.  

I Also use the IPTV Plugin for my HDHomeRun Prime cable tuner here in the US and would like to implement some sort of scanner to parse **PID/VPID/APIDs** into a channels.conf like so for scanning in Network Tuners.   I have forked your app and will continue to help with development and testing here in the US :) 

Example IPTV HDHomeRun channel for IPTV in vdr.
DISC HD;IPTV:5:S=0|P=1|F=HTTP|U=192.168.1.218/auto/v620|A=5004:I:0:**6321**:**6322**:0:0:**632**:0:0:0

**Comment by pipelka** [comment]
No way. This old legacy stuff was removed.
