### ISSUE TITLE
Full event-description in EPG guide (grid)

### ISSUE THREAD

**Issue by tunip** [pipelka/roboTV#5]
In the EPG guide we see title and subtitle but no full description of the event.

Would it be possible to implement full description per event in the EPG guide (grid)?

Thx

**Comment by pipelka** [comment]
All the information available for the EPG event is transferred to the Android TV database (also the short and the long event description).
The LiveTV app doesn't display the long description (don't know why).
It would be possible to add the long description to the shorter one but it would be truncated.

**Comment by tunip** [comment]
In the EPG guide (grid) the event title is shown 2 times. (title, title, subtitle)
Maybe it makes sense to change it to title, subtitle, description.
How many characters do we have for the description before its truncated?

**Comment by pipelka** [comment]
The EPG view is pre-defined by the system. Take a look at this:
http://developer.android.com/training/tv/tif/channel.html (Present Channel and Program Information)

The short description is limited to 256 characters:
http://developer.android.com/reference/android/media/tv/TvContract.Programs.html#COLUMN_SHORT_DESCRIPTION

I'll try to merge the descriptions and see how it looks like.

**Comment by pipelka** [comment]
It looks like this:

![epg-info](https://cloud.githubusercontent.com/assets/584386/12929131/80123cc2-cf71-11e5-8bdc-a6456fd047f0.jpg)
![epg-overview](https://cloud.githubusercontent.com/assets/584386/12929137/8536c20e-cf71-11e5-8d9b-eca7baa3ee91.jpg)

**Comment by tunip** [comment]
I like the additional (merged) information. Of course you never read the full plot of an event. But it gives you a small idea about the content of the event.

**Comment by pipelka** [comment]
I also think it's an improvement. Will cleanup the code and commit.
