### ISSUE TITLE
[robotv-atv] massive code refactoring & dataservice sync change

### ISSUE THREAD

**Issue by mattgorski** [pipelka/roboTV#52]
@pipelka just curious how did you refactor the entire app back in 2017?  Just following Googles sample TIF commit history? = https://github.com/googlesamples/androidtv-sample-inputs/commit/c00a14f67bdbffd501dfe7080c8d0bd106ae4cb0#diff-d521f765a49c72507257a2620612ee96

https://github.com/pipelka/roboTV/commit/ee4a97eede03749e6484ffc780a010f4542e9a45

I am facing the same issues (account sync errors, null pointers) with this iptv source I am trying to build to use streamdev-server for iptv transcoding with xmltv epg: https://github.com/Plex-VDR-HDHomerun/packages_apps_IPTV

Tvirl is very similar but i'd like to learn building TIF and add Time-shift support eventually....

**Comment by pipelka** [comment]
Take a look at the code.
Please do not abuse me and my project to get yours done.

**Comment by mattgorski** [comment]
I apologize pipelka, I can certainly read through the commit history...
