### ISSUE TITLE
Building with recent NDK fails

### ISSUE THREAD

**Issue by timolavi** [pipelka/roboTV#53]
Building with recent NDK fails, because in version r17c:

"Support for ARMv5 (armeabi), MIPS, and MIPS64 has been removed. Attempting to build any of these ABIs will result in an error"

and ffmpeg somhow requires it.
As fiirst time Android SDK user I was hapy to manage to downgrade it to version 16b and build and install RoboTV were succesfull.

**Comment by pipelka** [comment]
Check out the latest release 0.9.0.
