### ISSUE TITLE
Subtitles are missing

### ISSUE THREAD

**Issue by timolavi** [pipelka/roboTV#54]
I would like to Robotv play my Vdr-recordings, but there are no Dvb-subtitiles. Is it somehow possible to get subtitiles working there. Exoplayer seems to support them. I can do testing with subtitiles, but with my knowledge about java-programming and robotv-structure it is not possible to it myself.

**Comment by pipelka** [comment]
Sorry. Subtitles are currently not implemented.

**Comment by overas** [comment]
Exoplayer support dvb subtitles now, but robocopy do not build with the newest exoPlayer version. 

In Android Studio I tried to change in the file build.gradle:
`exoPlayerVersion='2.6.1' to exoPlayerVersion='2.10.1'.`

When building apk I get this error:
`error: FfmpegDecoder is not abstract and does not override abstract method createUnexpectedDecodeException(Throwable) in SimpleDecoder`

![image](https://user-images.githubusercontent.com/37910044/59827482-1ec29b80-9339-11e9-86ef-87c52152e830.png)

I hope you can find time and motivation to look at this issue. Robotv is a great project.

**Comment by pipelka** [comment]
Hmm, .. what should i say.
roboTV only works with the exoplayer version it was designed for.
