### ISSUE TITLE
EPG Partially Loaded

### ISSUE THREAD

**Issue by stahlhelmknacker** [pipelka/roboTV#58]
Hello pipelka,
Thank you for your work! The RoboTV app is working on the S905W with the ATVXperience ROM. Nevertheless, I have the problem that the EPG data is not loaded except for one channel (ORF III HD). Is there any possibility to force the update or do any debug on the VDR site? I am running the VDR 2.4.0 and the RoboTV APK 0.7.3. 

Thank you very much for your support!

**Comment by tveimo** [comment]
Would be good with an option to force reloading EPG data. I'm currently struggling with "no title" issues myself.

**Comment by pipelka** [comment]
Check out the latest release 0.9.0.
