### ISSUE TITLE
satip

### ISSUE THREAD

**Issue by engalaaodeh** [pipelka/roboTV#59]
supported for satip and if not it is  possible to add this feature please ?

**Comment by Schischu** [comment]
Sat-IP works fine. I am using RoboTV to steam Sat-IP from my Fritz-Box Cable box.
I had to set the following ENV for the docker image:
![image](https://user-images.githubusercontent.com/145518/90983982-66af0500-e572-11ea-9333-15168ea08339.png)

**Comment by pipelka** [comment]
Support for SAT <IP is available. Check the README of the VDR plugin.

**Comment by engalaaodeh** [comment]
many thanks for your support,
