### ISSUE TITLE
VDR events-images in  EPG guide (grid)

### ISSUE THREAD

**Issue by tunip** [pipelka/roboTV#6]
I use epgd/epg2vdr with a epgdata.com subscription and have a lot of images for many events in /var/cache/vdr/epgimages directory.

e.g.
/var/cache/vdr/epgimages/63745403_l.jpg

Would it be possible to implement these event-images from /var/cache/vdr/epgimages for the EPG guide (grid)?

Than you have both TMDb and VDR event images to show in the EPG guide.
TMDb has maybe the higher prio or the user can configure this in the settings.

Thx

**Comment by pipelka** [comment]
epg poster art must be delivered as URL to the TV database. So it would be possible to let the client check if an epg image is available at some url. 

E.g: http://my.artwork-server.com/path/%i.jpg (with %i as event id)

If this image exists the client could inject it into the roboTV artwork database.
The downside would be that the first epg sync would take longer.

**Comment by tunip** [comment]
If you could configure this optional in the roboTV setup like "Enter the artwork webserver address (http://.../path)" with a note about the long initial epg sync time, then it is a small improvment.

**Comment by tunip** [comment]
Alternatively a second scraper for tv shows like http://thetvdb.com/ could be used for more nice artwork.

**Comment by pipelka** [comment]
I'm currently refactoring the artwork handling. I think it would be best to define the url to the epg-images on the server and push it to the clients (single point of configuration).

thetvdb.com really seems to be more suitable for tv shows, ...

One major problem currently is that epg events of some providers do not fill in the content id correctly. Additional parsing of subtitle / description has to be done to figure out the type of the event.

**Comment by pipelka** [comment]
Here is a new testbuild including this feature:
https://www.dropbox.com/s/kc585gr20xx480e/robotv-master-fd5362e-release.apk?dl=0

You need to install the new robotv plugin on the server:
https://github.com/pipelka/vdr-plugin-robotv

Configuration is here:
https://github.com/pipelka/vdr-plugin-robotv/blob/master/robotv/robotv.conf

**Comment by tunip** [comment]
Many thanks for this testbuild. It works great. Time of loading the EPG data with its images is better than I expected.

Nice improvment (all EPG images on the screenshots are loaded via HttpEpgImageProvider) :+1: 
![leanback-ubersicht_20160222_120235](https://cloud.githubusercontent.com/assets/11404472/13218745/d7ff3fe4-d96b-11e5-8752-092fd0e16434.jpg)
![live channels_20160222_120125](https://cloud.githubusercontent.com/assets/11404472/13218747/dd5cc894-d96b-11e5-91b0-96558503536a.jpg)
![live channels_20160222_120225](https://cloud.githubusercontent.com/assets/11404472/13218749/df8a5fc8-d96b-11e5-9c9a-faf064ff75b5.jpg)

**Comment by pipelka** [comment]
Wow, looks really nice. I'll create a new release if there aren't any new issues with the new robotv vdr plugin arising.

**Comment by hannemann** [comment]
I use the same setup as tunip and i would like to integrate my epgimages aswell but i don't get how.

Do i need an additional sevice within my setup?

**Comment by tunip** [comment]
@hannemann You only need a webserver (e.g. Lighttpd, Apache, etc.) with a path to your epgimages and a entry in your vdr/plugins/robotv.conf like this:
EpgImageUrl = http://192.168.178.10/epgimages/%d_0.jpg

You can test it before with a web-browser and a valid epg-event:
http://192.168.178.10/epgimages/35688_0.jpg

If you want channel logos, you need a webserver too.

**Comment by hannemann** [comment]
Thanks for your reply.

Finally i got it working yesterday with Apache. Channellogos are much more tricky but work aswell

**Comment by tunip** [comment]
@hannemann 
if you also need a small eventsview.sql (epgd) which only shows the relevant information for Live Channels (see my screenshots above):

```
CREATE VIEW eventsview as select cnt_useid useid, cnt_eventid eventid, cnt_channelid channelid, cnt_source source, all_updsp updsp, cnt_updflg updflg, cnt_delflg delflg, cnt_fileref fileref, c
nt_tableid tableid, cnt_version version, sub_title title, case
 when sub_shorttext is null or sub_comptitle=sub_compshorttext or (substring(sub_shorttext,1,1)='S' and substring(sub_shorttext,2,1) REGEXP ('[0-9]')) then
  case when sub_genre is null then '' else concat(sub_genre,' (', sub_country, ' ',sub_year, ')') end
 else sub_shorttext
end shorttext,
cnt_starttime starttime, cnt_duration duration, cnt_parentalrating parentalrating, cnt_vps vps, cnt_contents contents, replace(
concat(
  case when epi_season is Null then '' else concat('Staffel ',cast(epi_season as char),', ') end,
  case when epi_part is Null then '' else concat('Folge ',cast(epi_part as char),'|') end,
  case when sub_source = 'epgdata' then
     case when sub_rating like '%Allgemein *****%' then concat('Bewertung: Sehr empfehlenswert')
          when sub_rating like '%Allgemein ****%' then concat('Bewertung: Empfehlenswert')
          when sub_rating like '%Allgemein ***%' then concat('Bewertung: Eher durchschnittlich')
          when sub_rating like '%Allgemein **%' then concat('Bewertung: Eher nicht empfehlenswert')
          when sub_rating like '%Allgemein *%' then concat('Bewertung: Eher uninteressant')
     else ''
     end
  else
     case when sub_numrating = 5 then concat('Bewertung: Einer der besten Filme aller Zeiten')
          when sub_numrating = 4 then concat('Bewertung: Sehr empfehlenswert')
          when sub_numrating = 3 then concat('Bewertung: Empfehlenswert')
          when sub_numrating = 2 then concat('Bewertung: Eher durchschnittlich')
          when sub_numrating = 1 then concat('Bewertung: Eher uninteressant')
     else ''
     end
  end,
  case when sub_shortreview is Null then '' else concat(' (',sub_shortreview,')') end,
  case when sub_rating is null and sub_numrating is Null then '' else '|' end,
  case when sub_longdescription is Null then '' else concat(sub_longdescription) end
)
,'|', '
') as description
from
 useevents;
```

**Comment by hannemann** [comment]
Thanks, but i need the default view in my Restfulapi Webapp.
