### ISSUE TITLE
Smartphone version?

### ISSUE THREAD

**Issue by kodidu** [pipelka/roboTV#60]
Is it possible to run the android tv apk on a android phone/tablet?

**Comment by pipelka** [comment]
It's not intended to run on Android. It's designed for Android TV / Google
TV.
The Live TV subsystem is not part of Android.
It's open-source. One could make it run on plain Android.
But not me, ...


kodidu <notifications@github.com> schrieb am Sa., 26. Dez. 2020, 14:18:

**Comment by kodidu** [comment]
Ok, i would like try it out, but i have no android TV box yet.
I installed the android TV x86 in a virtual machine.
Could you offer a x86 android TV apk?

**Comment by pipelka** [comment]
Sorry. You need to install AndroidStudio and compile the latest version.
The current APK is totally outdated (from 2017).


Am Sa., 26. Dez. 2020 um 15:09 Uhr schrieb kodidu <notifications@github.com

**Comment by kodidu** [comment]
Do you have an arm apk around for testing?
https://travis-ci.org/github/pipelka/roboTV does not save build artifacts?

**Comment by pipelka** [comment]
Well, saving build artifacts could be the way.
Maybe you're able to create a PR for the travis-ci configuration to save
build artifacts ?


Am Sa., 26. Dez. 2020 um 15:22 Uhr schrieb kodidu <notifications@github.com

**Comment by pipelka** [comment]
To shorten this procedure:

there is a new release of the APK available at:
https://github.com/pipelka/roboTV/releases/tag/0.9.0

Try to install it to any device you like, but please don't complain if it's not working on any non Android TV device.
