### ISSUE TITLE
Version 0.9.1 is not Working at Xiami TV Stick Android TV 9

### ISSUE THREAD

**Issue by TimUx** [pipelka/roboTV#61]
Hi,
i can install the new Release, but when I've try to open it, the screen becomes black for an short time an went back to Home-Screen.

Version 0.7.3 is working fine, ...

**Comment by pipelka** [comment]
Should be fixed with 0.9.2.
The debug build didn't show the real problem.

**Comment by TimUx** [comment]
Hi,
yep the App is running now.

Live Channels runs like hell, but i could not playback a record.

Again black-screen and after a short while, it goes back to the Records Page.

**Comment by pipelka** [comment]
Aargh,..
I really hate these inconsistencies with different API levels.
I'll take a look. Again, ...

**Comment by pipelka** [comment]
Ok. Again.
Please try version 0.9.3

**Comment by TimUx** [comment]
Hi,
no luck, still no playback of records.

I'd like to test it at my Sony TV also, but it has Android 7, so the new versions could not be installed.

**Comment by pipelka** [comment]
Are you able to start the playback via the 'Recommendations Channel' on the homescreen ?
Version 0.9.3 is running flawlessly on my Xiaomi Mi box now.
With some changes a can make it run on Android TV 7.1.1 (API Level 25).

**Comment by TimUx** [comment]
Hi,
no, i can't start Records via homescreen.

Black Screen for a short time and Back to the Homescreen.

Do i need the latest and greatest vdr-plugin version for the new Android Client.
At the Moment, I'am some versions lower.

PS: Bei Bedarf können wir auch deutsch schreiben. ;-)

**Comment by pipelka** [comment]
Newest client -> newest VDR plugin.
This could be the reason. The 0.9 client uses a new backend call to fetch information about the recording.

**Comment by TimUx** [comment]
OK, 
i will try it with a new docker installation and will write to Claus Muus, so he can Upgrade MLD 5.4 with the newest vdr-plugin.

**Comment by pipelka** [comment]
Great. The 'master' branch should run now on devices with a minimum Android TV version of 7.0 (API Level 24).
At least it's working in the emulator, ...
I can push out a 0.9.4 release apk if you want to try it on the older Sony TV.

**Comment by TimUx** [comment]
Sure,
i will give it a try, ...

I've posted a thread at the minidvblinux Forum.
So i Hope, Claus will add the new vdr-plugin version shortly in MLD 5.4

**Comment by pipelka** [comment]
Please test this apk before I will a wrap up a new release:
https://www.dropbox.com/s/msjblfl6693tqdv/robotv-0.9.4-pre1.apk?dl=0

**Comment by TimUx** [comment]
Hi,
no Problem with this Version at my old 2015er Sony TV.

I will waiting now for the MLD Upgrade by Claus and report, if i can playback the records.

**Comment by pipelka** [comment]
One more thing. I just created a new apk:
https://www.dropbox.com/s/7j1ud3vokyifqem/robotv-0.9.4-pre2.apk?dl=0

This version should not crash with older server plugins but show an error message.
Could you please try this one.

**Comment by TimUx** [comment]
Hi,
ich bin erst einmal unterwegs und teste es heute Abend.

Gruß Timo

**Comment by TimUx** [comment]
Läuft, ...

Es kommt die Fehlermeldung, dass die Filminformationen nicht abgerufen werden können.

Nach der Meldung bleibt es allerdings beim schwarzne Bildschirm.
Vielleicht wäre es besser wieder ins RoboTV Menü zu springen.

**Comment by pipelka** [comment]
Vielen Dank.
Ich wollte nur sicherstellen dass die Fehlermeldung kommt und keine andere Ursache vorliegt.
Ich werde noch ändern das dass Fenster nach der Meldung geschlossen wird.

Ok. 0.9.4 kommt dann im neuen Jahr.
Prosit.

**Comment by TimUx** [comment]
Alles klar,
wenn ich sonst mal weiterhelfen bzw etwas testen kann, einfach melden.
Ich bin auch offzieller Tester von MLD.

Ansonsten Danke für das Tool und die gute Arbeit!

Wenn man jetzt noch Schnittmarken bearbeiten könnte, würde mein RPI als VDR Client komplett weg fliegen. ;-)

In diesem Sinne, einen guten Rutsch ins neue Jahr!

Gruß Timo

**Comment by pipelka** [comment]
Ok. Mit Version 0.9.4 sollte das Thema nun beendet sein:
https://github.com/pipelka/roboTV/releases/tag/0.9.4

Die Schnittmarken können wir gerne in einem eigenem 'Issue' diskutieren.
