### ISSUE TITLE
channel change issue

### ISSUE THREAD

**Issue by tunip** [pipelka/roboTV#8]
Some channels are not switched on the first try (screen stays black after channel switch). For example "n-tv HD" needs mostly 5 trys or more to switch successfully. I comapred the VDR logs with version 0.1 (works fine) and 0.2. There is no difference if its works on frist try or on 5 or more.

This behavior happens also on version 0.1 but mostly on second try channel will be switched successfully.

Is it possible to configure the 3 second timeout value?

I have to mention, that I use satip (plugin version 2.2.3) with a OctopusNet DVB-S2.

**Comment by tunip** [comment]
No change if i start xvdr plugin with "-t 10" (default is 3 not 10 seconds)

**Comment by pipelka** [comment]
Strange. Doesn't happen for me.
Sounds like a problem on the client. I just walked through (short) the change log and didn't find many serious changes that could cause this.

But maybe there is one change responsible for this. Please try this testbuild (signed apk):
https://www.dropbox.com/s/gprkjw56p35ufv5/robotv-master-a235b4a-release.apk?dl=0

Maybe it makes a difference for you.

**Comment by tunip** [comment]
Thanks for this testbuild. Unfortunately the behavior is the same as in version 0.2. Also FTA channels (3sat HD) are affected. There some channels they work fine on the first try like "Das Erste HD", "Prosieben HD", "N24 HD". And there some problematic channels like "n-tv HD", "RTL HD" they never switch on first try. And there are some channels like "3sat HD" they sometimes work on first try and sometimes on the second try.

With verion 0.2 if I switch channel from "Das Erste HD" to "ZDF HD" after 3-5 seconds i can hear audio with a standpicture and after another 3-5 seconds i also have video. So channelswitchting works but needs round about 8 seconds.

Best results are with version 0.1, today (after felt 150 channel changing) every channel switch works.

**Comment by pipelka** [comment]
OK. Thanks for testing. So it might be a problem with ExoPlayer. I'll create a new testbuild with the ExoPlayer version from 0.1 today in the evening.

**Comment by pipelka** [comment]
Alright. After bisecting the sources i think i found the issue. I was able to reproduce this behavior also on the Nexus Player.

Ok. Please try this testbuild:
https://www.dropbox.com/s/epoxmd1mcc9osyn/robotv-master-bc3d2c3-release.apk?dl=0

**Comment by tunip** [comment]
With the last testbuild it looks much more better now. I switched the whole channellist up and down and every change was fine. Also audio and video starts together.

**Comment by pipelka** [comment]
Great. Thanks. I'll push the fix and close the issue.
