### ISSUE TITLE
Blank screen with video but audio is OK

### ISSUE THREAD

**Issue by smoothquark** [pipelka/roboTV#9]
Got a problem running on the nvidia shield android TV. I can browse the channels but no video. Audio works OK. It was working OK with one of the earlier builds (cannot remember which one) but I get this problem with version 0.2.0. Reverting back to the previous apk does not make a difference, nor does rebooting.
Interestingly, I had a similar issue with the Google live channels sample app. Upgrading that app resolved the issue.
I am wondering if this problem might be due to exoplayer? I wonder if somehow exoplayer remains even if the app is removed and the only way to resolve is to have a newer version of exoplayer?

**Comment by pipelka** [comment]
ExoPlayer is bundled with roboTV and will not survive deinstalling the app.
Please try the testbuild from #8. I think it might be the same problem.

Try to deinstall the app first and then install the new version.

**Comment by pipelka** [comment]
Please try this build:
https://www.dropbox.com/s/epoxmd1mcc9osyn/robotv-master-bc3d2c3-release.apk?dl=0

**Comment by smoothquark** [comment]
Not working either. I seem to recall version 0.2.0 might have been OK initially, but suddenly the screen problem cropped up. Videos work fine via Kodi and built it mediaplayer

**Comment by pipelka** [comment]
Funny thing. I have no clue why this should happen.

Maybe you can provide some logs from the server and the client (adb logcat).

BTW, are you using vdr on a dedicated server ?
I recently found that there's still a bug in the xvdr plugin causing a device lockup under certain conditions. A restart of vdr could help in this case.

**Comment by smoothquark** [comment]
Got 0.2.0 working again. I think the problem is with exoplayer. I ended up doing a factory reset. Still testing though. My VDR is on a dedicated server and getting to gtips with it. Used to use tvheadend all this while but it does not have an android TV interface. I do like the work you have done so far and shall be trying your recording branch soon.

**Comment by pipelka** [comment]
Very strange. I can't imagine that exoplayer should cause this. But who knows,...

The "recordings" branch isn't ready for prime time yet. It is basically presenting all recordings and playback should work (somehow) but seeking is currently completely broken. This is the next thing on my todo list. Nevertheless you are welcome to test it.

My plan is to get recordings working until 1.0 and then publish it on the Play Store. Timeframe should be approximately till the end of the year.

BTW, [0.3.0](https://github.com/pipelka/roboTV/releases/tag/v0.3.0) is available.

**Comment by pipelka** [comment]
Ok. Closing. Seems to be resolved.
